### ISSUE TITLE
US-4 - Fonctions invitées

### ISSUE THREAD

**Issue by Tristan-Evenot** [YummYume/modulo#20]
En tant qu’admin, je peux définir quelles fonctions sont invitées par défaut à une catégorie d’événement.

**Comment by LeoBruant** [comment]
Dépend de #17

**Comment by YummYume** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [US-4 - Fonctions invitées](https://trello.com/c/pbB0BPkL/14-us-4-fonctions-invit%C3%A9es)
