### ISSUE TITLE
US-38 - Invité par fonction

### ISSUE THREAD

**Issue by YummYume** [YummYume/modulo#27]
En tant qu’utilisateur, je suis invité à un événement si la structure associée à au moins un de mes scopes fait partie des structures invitées ou est enfant de l’une d’elles et que la fonction de ce même scope est invitée.

**Comment by LeoBruant** [comment]
Je suis invité à un événement si au moins une de mes scopes est invitée, ou si une de mes structures est l'enfant d'un rôle invité.
