### ISSUE TITLE
US-14 - Accueil connecté

### ISSUE THREAD

**Issue by LeoBruant** [YummYume/modulo#3]
En tant qu’utilisateur, une fois connecté, sur la page d’accueil je dois voir mes scopes disponibles et si mon profil le permet, je peux aussi accéder à l’agenda et à la création d’un nouvel événement.

**Comment by YummYume** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [US-14 - Accueil connecté](https://trello.com/c/VGBJfnk5/18-us-14-accueil-connect%C3%A9)
