### ISSUE TITLE
US-15 - Changement de scope

### ISSUE THREAD

**Issue by LeoBruant** [YummYume/modulo#4]
En tant qu’utilisateur connecté, à tout moment je peux changer de scope en choisissant parmi tous ceux disponibles.

**Comment by LeoBruant** [comment]
En tant qu’utilisateur connecté, à tout moment je peux changer de scope en choisissant parmi tous ceux disponibles.

**Comment by YummYume** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [US-15 - Changement de scope](https://trello.com/c/hxlmSG64/20-us-15-changement-de-scope)
