### ISSUE TITLE
US-1 - Habilitations par fonction

### ISSUE THREAD

**Issue by Tristan-Evenot** [YummYume/modulo#5]
En tant qu’admin je peux définir pour chaque fonction quelles sont les fonctionnalités autorisées.

**Comment by LeoBruant** [comment]
Créer un enum fonctionnalité

**Comment by YummYume** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [US-1 - Habilitations par fonction](https://trello.com/c/y2LX5zy3/13-us-1-habilitations-par-fonction)
